version: '1'
services:
    app:
        container_name: docker-node-mongo
        restart: always
        build: .
        ports:
            - '80:4000'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
    adminmongo:
        container_name: admin-mongo
        image: mrvautin/adminmongo
        restart: always
        environment:
            - HOST=0.0.0.0
        ports:
            - '1234:1234'
